config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :users,only: [:index,:show,:edit,:update]
  resources :books,only: [:index,:create,:show,:edit,:update,:destroy]
  get 'home/about',to:'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy

 has_one_attached :profile_image

  validates :name, length: { minimum: 2 ,maximum: 20},uniqueness: true
  validates :introduction, length: {maximum: 50}
  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
  #   super
   end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_matching_login_user, only: [:edit, :update]

  def index
      @users = User.all
      @user = current_user
  end

  def show
      @user = User.find(params[:id])
      @books = Book.all
      @user_books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
     @user.update(user_params)
     if @user.save
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path
     else
       render :edit
     end
  end

   private

  def is_matching_login_user
    user = User.find(params[:id])
    if current_user.id !=user.id
       redirect_to user_path(current_user.id)
    end
  end
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>User info</h2>
     <% if @user.errors.any? %>
  <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
     <%= form_with model: @user do |f| %>
     <br>
      <label for="user_name">Name</label>
      </br>
       <%= f.text_field :name %>
      <br>
      <p id="notice"></p>
      <label for="user_image">Image</label>
      </br>
       <%= f.file_field :profile_image %>
      <br>
      <p id="notice"></p>
      <label for="user_introduction">Introduction</label>
      </br>

       <%= f.text_area :introduction %>
       <br>
       <p id="notice"></p>
        <%= f.submit 'Update User',class:"btn btn-secondary" %>
        <% end %>
        </br>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
    <div class="row">
     <%= render 'books/list',user: @user %>
      <div class="col-md-8 offset-md-1">
       <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
             <th>image</th>
             <th>name</th>
             <th></th>
            </tr>
          </thead>
         <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
               <%= image_tag user.get_profile_image(100,100) %>
              </td>
              <td><%= user.name %>
              </td>
              <td><%= link_to "Show", user_path(user) %>
              </td>
            </tr>
          </tbody>
         <% end %>
        </table>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
    <div class="row">
     <%= render 'books/list',user: @user %>
     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
          <thead>
            <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
            </tr>
          </thead>
         <% @user_books.each do |book| %>
          <tbody>
            <tr></tr>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                 <%= image_tag @user.get_profile_image(100,100) %>
                 <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
         <% end %>
        </table>
    </div>
</div>