config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :users,only: [:index,:show,:edit,:update]
  resources :books,only: [:index,:create,:show,:edit,:update,:destroy]
  get 'home/about',to:'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_user, only: [:edit, :update]

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = current_user
    @book_user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
    <div class="col-md-3">

     <h2>User info</h2>
      <%= image_tag user.get_profile_image(100,100) %>
      <table class="table table-striped">
       <tbody>
        <tr></tr>
        <tr>
         <th>name</th>
         <th><%= user.name %></th>
        </tr>
        <tr></tr>
        <tr>
         <th>introduction</th>
         <th><%= user.introduction %></th>
        </tr>
       </tbody>
      </table>
      <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
      <% end %>
      <h2 class ="mt-3">New book</h2>

      <%= form_with model: Book.new do |f| %>
      <br>
       <label for="book_title">Title</label>
       </br>
         <%= f.text_field :title %>
         <p id="notice"></p>
       <br>
       <label for="book_opinion">Opinion</label>
       </br>
         <%= f.text_area :body %>

           <%= f.submit 'Create Book',class:"btn btn-success" %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
           <% @book.errors.full_messages.each do |message| %>
           <li><%= message %></li>
           <% end %>
        </ul>
        <% end %>
      <%= form_with model: @book do |f| %>
         <br>
         <label for="book_title">Title</label>
         </br>
         <%= f.text_field :title %>
        <p id="notice"></p>
        <br>
        <label for="book_opinion">Opinion</label>
        </br>
         <%= f.text_area :body %>
         <p id="notice"></p>
           <%= f.submit 'Update Book',class:"btn btn-success" %>
           <% end %>
           <p id="notice"></p>
          <%= link_to "Show", book_path(@book.id) %>
          <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
         <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
       <ul>
         <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
         <% end %>
       </ul>
     <% end %>
    <div class="row">
       <%= render 'books/list',user: @user %>

      <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
            </tr>
          </thead>
         <% @books.each do |book| %>
          <tbody>
            <tr></tr>
            <tr>
              <td><%= link_to user_path(book.user) do %>
               <%= image_tag book.user.get_profile_image(100,100) %>
               <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
         <% end %>
        </table>
      </div>
    </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
    <div class="row">
     <%= render 'list',user: @book_user %>

      <div class="col-md-8 offset-md-1">
       <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr></tr>
            <tr>
             <td>
              </td>
              <td>
               <%= link_to (@book.user) do %>
               <%= image_tag @book.user.get_profile_image(100,100) %>
               <br><%= @book.user.name %>
               </br>
               <% end %>
              </td>
              <td>
               <%= link_to @book.title, book_path(@book) %>
               </td>
              <td>
               <%= @book.body %>
               </td>
              <td><% if @book.user == current_user %>
                  <%= link_to "Edit",edit_book_path(@book),class:"btn btn-sm btn-success edit_book" %>
                  <% end %>
              </td>
              <td><% if @book.user == current_user %>
                  <%= link_to "Destroy",book_path(@book),class:"btn btn-sm btn-danger", method: :delete,"data-confirm" => "本当に削除しますか？" %>
                  <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
</div>